### PR TITLE
test(shouldAdvanceTime): add test that check that time is still updated even with sync work

### PR DESCRIPTION
**Pull request by rluvaton**
#### Purpose (TL;DR) - mandatory

Adding test case for #422

### CODE REVIEW

**Comment by rluvaton** [comment]
@benjamingr

**Review by benjamingr — APPROVED** [review]

**Comment by rluvaton** [comment]
I think you should stop the tests this will just run until killed, the tests are stuck because of the sync code

**Comment by benjamingr** [comment]
Ok, talked about how to fix it by waiting for a timer on whatsapp

**Comment by rluvaton** [comment]
Closing, see https://github.com/sinonjs/fake-timers/issues/422#issuecomment-1038403540 why

**Pull request closed without merging**
