### PR TITLE
feat: warpFactor

### PR DESCRIPTION
**Pull request by Noriller**
#### Purpose (TL;DR) - mandatory

Adding feature: `warpFactor` that changes the normal delay/timeout by the factor provided.
Issues: #459 #16 

This is a dependency of Jest that is widely used. In frontend testing, many component libraries abstract micro animations that take time to complete and slow down testing.

Using fake timers would mean having to spam methods to run the timers, which is not optimal.

This PR aims to add a way to speed up all those hidden timers without anything more than passing a flag with the factor to be used.

Mainly, I added the `warpFactor` to the config and when present, it takes the delay and divides it by the factor.

The one thing I want to highlight is that if the factor is higher than the timeout, then the timeouts are rounded to zero. 

This would throw off the ordering of timers, since you can possibly make all timers 0. So I added something to keep track of what would be the actual `callAt` to make use in the compare timers function.

I'm not sure in what scenario it could be useful, but this implementation also lets you use an fraction as the `warpFactor`, making all timeouts run slower than normal.

### CODE REVIEW

**Review by benjamingr — COMMENTED** [review]
The code itself is good but I don't really understand the feature. I don't understand the motivation to not just `.tick(n * 100)` instead of this?

Also wouldn't it be simpler to just progress `.tick` calls by warpFactor * passedTime instead of modifying the timers themselves?

**Comment by Noriller** [comment]
At the time I didn't think of that.
I screw up this PR, so I'll be opening a new one with the changes.

**Review by benjamingr — COMMENTED** [review]
Nice the code looks good to me and the implementation looks fine - I am not sure about the feature itself still.

@fatso83 @SimenB wdyt? I think OP makes a compelling case but I'm hesitant approving a feature I don't fully understand the usage of in real life.

**Comment by fatso83** [comment]
Yeah, as Simen asked (to be answered) in the original issue, I also don't understand the usecase or what isn't handled by .runAll() or tick(n*1000).

**Comment by fatso83** [comment]
See  https://github.com/sinonjs/fake-timers/issues/459#issuecomment-1936981297. 

This is not a full stop! It can be reopened if someone provides a good usecase for why this is needed and makes sense!

**Pull request closed without merging**
