### PR TITLE
add hasRef

### PR DESCRIPTION
**Pull request by soferdani**
#### Purpose (TL;DR) - mandatory

add refed attribute to the res object

-----
add this as required in the issue - Missing hasRef for Node #408

### CODE REVIEW

**Review by benjamingr — APPROVED** [review]
Looks good to me :)

**Comment by SimenB** [comment]
Tests? 😀

**Comment by fatso83** [comment]
Yeah, realize we are talking about a handful of lines here, but a little test to demonstrate use would be nice

**Comment by soferdani** [comment]
Sorry for the delay, I added the tests as you asked (I hope..) Please let me know if you think I need to add/remove something.

**Review by benjamingr — APPROVED** [review]

**Comment by fatso83** [comment]
This failed due to not running Prettier (which I fixed for you), but the tests fail as well in Chromium, since there is no conditional checking here.

**Pull request merged**
