### PR TITLE
add unit test for issue#504

### PR DESCRIPTION
**Pull request by erossignon**

### CODE REVIEW

**Comment by fatso83** [comment]
@erossignon I think you missed that I made a fix half an hour ago. Check your original issue 😄

**Comment by fatso83** [comment]
Thank you very much for the unit test, but I already supplied one in the PR:
https://github.com/sinonjs/fake-timers/commit/ae0a2665c68576387452dda1abae7425c1779416#diff-5a5796b4730f7629082606dc9407d4b8a084ab5ec38803e6141743b4bbb9f7efR3373

It should cover the same ground, no?

**Comment by erossignon** [comment]
My test was a little bit more black box than yours.  No worries.

**Comment by fatso83** [comment]
I did see that, which was attractive :)

**Pull request merged**
