### PR TITLE
Convert timer delay to number if not already

### PR DESCRIPTION
**Pull request by arielweinberger**
#### Purpose
Fix issue #315 by checking if `timer.delay` is a number. If it isn't make it one by parsing it to an integer.

### CODE REVIEW

**Comment by benjamingr** [comment]
Hey this looks cool - would you mind adding a test?

**Comment by benjamingr** [comment]
(Tests are basically one big file https://github.com/sinonjs/fake-timers/blob/master/test/fake-timers-test.js )

**Comment by arielweinberger** [comment]
@benjamingr test added

**Comment by benjamingr** [comment]
Thanks!

**Pull request merged**
